name: firebase_integration
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core:
  firebase_auth:
  google_sign_in:
  firebase_in_app_messaging:
  flutter_local_notifications:
  flutter:
    sdk: flutter
  firebase_messaging: ^11.4.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

